---
title: "PS4 Solution"
output:
  pdf_document: default
  html_notebook: default
---

### import libraries
```{r}
library(haven)
library(tidyverse)
library(labelled)
library(ggthemes)
library(cowplot)
```

### Data cleaning
```{r}
raw_data <- read_dta("ns20200625.dta")
names(raw_data)

table(raw_data$citizen)


reduced_data <- 
  raw_data %>% 
  select(
    region,
    stateicp,# 
    sex,  #
    age, #
    race, #
    hispan,#
    bpl,#
    educd,#
    empstat, #
    ftotinc) #


ACS <- reduced_data
ACS <- subset(ACS, age > 17) 
ACS <- subset(ACS, age < 94) 



ACS$bpl = cut(ACS$bpl,c(0,56,999))
levels(ACS$bpl) = c('USA', 'another country')


ACS$sex <- cut(ACS$sex, c(0,1,2))
levels(ACS$sex) <- c("male", "female")




ACS$educd = cut(ACS$educd,c(0,26,61,64,71,101,116), labels=c(1:6))
ACS$educd <- as.numeric(ACS$educd)

table(ACS$age)
ACS$age <- as.numeric(as.character(ACS$age))
ACS$age[is.na(ACS$age)] <- 90
ACS$age = cut(ACS$age,c(17, 29, 44, 59, 74, 93))
levels(ACS$age) = c('18 to 29', '30 to 44',
                     '45 to 59', '60 to 74',
                     '74 and above')


table(ACS$age)
nrow(ACS) == nrow(ACS) 



ACS$empstat <- labelled::to_factor(ACS$empstat)
ACS$empstat <- as.character(ACS$empstat)


# INCOME

ACS$ftotinc = cut(ACS$ftotinc,c(-16400,14999,19999,24999,29999,34999,
                                39999,44999, 49999,54999,59999,64999,
                                69999,74999,79999,84999,89999,94999,
                                99999,124999,149999,174999, 199999,
                                249999, 9999998, 9999999), labels=c(1:25))
ACS$ftotinc <- as.numeric(ACS$ftotinc)
ACS$ftotinc[ACS$ftotinc == 25] <- NA

levels(ACS$ftotinc) = c('Less than $14,999', '$15,000 to $19,999', '$20,000 to $24,999',
                       '$25,000 to $29,999', '$30,000 to $34,999', '35,000 to $39,999',
                       ' $40,000 to $44,999','$45,000 to $49,999','$50,000 to $54,999',
                       '$55,000 to $59,999', '$60,000 to $64,999', '$65,000 to $69,999',
                       '$70,000 to $74,999',   '$75,000 to $79,999',   '$80,000 to $84,999',
                       '$85,000 to $89,999', '$90,000 to $94,999', '$95,000 to $99,999',
                      '$100,000 to $124,999', '$125,000 to $149,999', '$150,000 to $174,999',
                       '$175,000 to $199,999', '$200,000 to $249,999',   '$250,000 and above',
                       NA
                       )
table(ACS$ftotinc)



ACS$race <- labelled::to_factor(ACS$race)
ACS$hispan <- labelled::to_factor(ACS$hispan)


ACS$race <- gsub("american indian or alaska native", "native american", ACS$race)
ACS$race <- gsub("japanese", "other asian/pacific islander", ACS$race)
ACS$race <- gsub("other asian or pacific islander", "other asian/pacific islander", ACS$race)
ACS$race <- gsub("other race, nec", "other", ACS$race)
ACS$race <- gsub("two major races", "other", ACS$race)
ACS$race <- gsub("three or more major races", "other", ACS$race)
ACS$race <- gsub("black/african american/negro", "black", ACS$race)
table(ACS$race)


ACS$hispan <- gsub("mexican", "hispanic", ACS$hispan)
ACS$hispan <- gsub("puerto rican", "hispanic", ACS$hispan)
ACS$hispan <- gsub("cuban", "hispanic", ACS$hispan)
ACS$hispan <- gsub("other", "hispanic", ACS$hispan)
table(ACS$hispan)


ACS$race <- ACS$race
ACS$race[ACS$hispan == 'hispanic'] <- "hispanic"
ACS$race <- as.character(ACS$race_ethnicity)
table(ACS$race)


ACS <- 
  ACS %>% 
  select(
    region,
    stateicp,
    sex,
    age,
    race, 
    bpl,
    educd,
    empstat, 
    ftotinc)



ACS$stateicp <- labelled::to_factor(ACS$stateicp)

ACS$stateicp <- as.character(ACS$stateicp)
ACS$stateicp <- as.factor(ACS$stateicp)

levels(ACS$stateicp) <- c(1:51)
ACS$stateicp <- as.numeric(ACS$stateicp)



colnames(ACS) <- c("census_region", "state", "gender", "age", "race_ethnicity", 
                   "foreign_born", "education", "employment", 
                   "household_income")

summary(ACS)

write_csv(ACS, "ACS.csv")  




raw_UCLA <- read_dta("ns20200625.dta")


# Just keep some variables that may be of interest (change 
# this depending on your interests)
names(raw_UCLA)

reduced_UCLA <- 
  raw_UCLA %>% 
  select(vote_2020, #
         employment, #
         foreign_born,#
         gender,#
         census_region, # (UNFINISHED, clean if needed)
         hispanic,#
         race_ethnicity, #
         household_income,#
         education, #
         state, #(UNFINISHED)
         age #
         )

UCLA <- reduced_UCLA

#deleting responses if not Trump(1)/Biden(2)
UCLA <- subset(UCLA, vote_2020 < 3 ) 
# Assign a vote for Joe Biden a value of 0
UCLA$vote_2020[UCLA$vote_2020 == 2] <- 0
UCLA$vote_2020 <- as.numeric(UCLA$vote_2020)
state.abb#deleting responses who picked "other" as employment
UCLA <- subset(UCLA, employment <= 8 )


# EDUCATION

UCLA$education = cut(UCLA$education,c(0,2,3,4,6,9,11), labels=c(1:6))

# levels(UCLA$education) = c('less than high school', 'some high school',
#                      'completed high school', 'some post-secondary',
#                      'post-secondary degree', 'post-graduate degree'
# )

UCLA$education <- as.numeric(UCLA$education)


# GENDER
UCLA$gender = cut(UCLA$gender,c(0,1,2))
levels(UCLA$gender) = c('female', 'male')
table(UCLA$gender)


# AGE
# put age into bins
UCLA$age = cut(UCLA$age,c(17, 29, 44, 59, 74, 93))
levels(UCLA$age) = c('18 to 29', '30 to 44',
                            '45 to 59', '60 to 74',
                            '74 and above')


# BIRTHPLACE

UCLA$foreign_born = cut(UCLA$foreign_born,c(0,1,2))
levels(UCLA$foreign_born) = c('USA', 'another country')
table(UCLA$foreign_born)


# RACE

#hispanic (make binary)
UCLA$hispanic = cut(UCLA$hispanic,c(0,1,15))
levels(UCLA$hispanic) = c('not hispanic', 'hispanic')
table(UCLA$hispanic)

#Simplifying/grouping UCLA races
UCLA$race_ethnicity = cut(UCLA$race_ethnicity,c(0,1,2,3,4,5,14,15))
levels(UCLA$race_ethnicity) = c('white', 'black',
                           'native american', 'other asian/pacific islander',
                           'chinese', 'other asian/pacific islander 1', 'other'
)
UCLA$race_ethnicity <- gsub('other asian/pacific islander 1', 'other asian/pacific islander', UCLA$race_ethnicity)
table(UCLA$race_ethnicity)

#RACE including hispanics as a race
UCLA$race_ethnicity <- UCLA$race_ethnicity
UCLA$race_ethnicity[UCLA$hispanic == 'hispanic'] <- "hispanic"
UCLA$race_ethnicity <- as.character(UCLA$race_ethnicity)

#discard hispanic column
UCLA <- 
  UCLA %>% 
  select(vote_2020, #
         employment, #
         foreign_born,#
         gender,#
         census_region, # UNFINISHED
         race_ethnicity, #
         household_income,
         education, #
         state, 
         age #
  )
table(UCLA$race_ethnicity)


# EMPLOYMENT
UCLA$employment = cut(UCLA$employment,c(0,1,3,4,5,7,8))
levels(UCLA$employment) = c('employed', 'not in labor force',
                            'unemployed', 'employed1',
                            'not in labor force1', 'employed2')
table(UCLA$employment)
UCLA$employment <- gsub('employed1', 'employed', UCLA$employment)
UCLA$employment <- gsub('employed2', 'employed', UCLA$employment)
UCLA$employment <- gsub('not in labor force1', 'not in labor force', UCLA$employment)
table(UCLA$employment)


# STATE
# Replace state abbreviations with state names, adding "DC" to the 
# state.abb vector and "district of columbia" to the state.name vector
UCLA$state <- append(state.name, values=c("district of columbia"))[match(
  UCLA$state, append(state.abb, values=c("DC")))]
# Make all state names lowercase
UCLA$state <- tolower(UCLA$state)
# Assign state names a numeric value between 1 and 51 in alphabetical order
UCLA$state <- as.factor(UCLA$state)
levels(UCLA$state) <- c(1:51)
UCLA$state <- as.numeric(UCLA$state)


###################################################################################
# Add the labels
UCLA <- labelled::to_factor(UCLA)



# INCOME
sum(table(UCLA$household_income))


table(UCLA$state)
nrow(table(UCLA$state))
sum(table(UCLA$state))

# create clean output file
write_csv(UCLA, "UCLA.csv")  
```


### Plot modeling
```{r}
ACS <- read_csv(("ACS.csv"), col_types = cols(census_region = col_character(), 
                                                           race_ethnicity = col_character(),
                                                           employment = col_character(),
                                                           gender = col_factor(),
                                                           age = col_factor(),
                                                           foreign_born = col_factor(),
                                                           state = col_number(),
                                                           education = col_number(),
                                                           household_income = col_number()
                                                           )
                )

# AGE
AGE <- ggplot(ACS, aes(x =age)) + 
  geom_bar(fill = 'steelblue', aes(y = (..count..)/sum(..count..))) + 
  scale_y_continuous(labels=scales::percent) +
  ylab("relative frequencies")+
  theme_minimal() +
  ggtitle("Age distribution in ACS")


# GENDER 
GENDER <- ACS  %>% group_by(gender) %>% summarise(n = n()) %>%
  mutate(prop = 100 * (n / sum(n))) 
GENDER <- GENDER %>%
  ggplot(aes(x="", y=prop, fill=gender)) +
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start=0) + 
  scale_fill_brewer(palette="Paired") +
  theme_void() + 
  ylab("") + xlab("") + 
  labs(title = "", fill="Gender ") + 
  geom_text(aes(label = paste0(round(prop), "%")), position = position_stack(vjust = 0.5), size = 4.7) +
  theme(text = element_text(size=15)) + ggtitle("Gender distribution in ACS")


# EMPLOYMENT
EMP <- ACS  %>% group_by(employment) %>% summarise(n = n()) %>%
  mutate(prop = 100 * (n / sum(n))) 
EMP <- EMP %>%
  ggplot(aes(x="", y=prop, fill=employment)) +
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start=0) + 
  scale_fill_brewer(palette="Paired") +
  theme_void() + 
  ylab("") + xlab("") + 
  labs(title = "", fill="employment ") + 
  geom_text(aes(label = paste0(round(prop), "%")), position = position_stack(vjust = 0.5), size = 4.7) +
  theme(text = element_text(size=15)) + ggtitle("Employment status distribution in ACS")


# RACE
RACE <- ACS  %>% group_by(race_ethnicity) %>% summarise(n = n()) %>%
  mutate(prop = 100 * (n / sum(n))) 
RACE <- RACE %>%
  ggplot(aes(x="", y=prop, fill=race_ethnicity)) +
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start=0) + 
  scale_fill_brewer(palette="Paired") +
  theme_void() + 
  ylab("") + xlab("") + 
  labs(title = "", fill="race ") + 
  geom_text(aes(label = paste0(round(prop), "%")), position = position_stack(vjust = 0.5), size = 4.7) +
  theme(text = element_text(size=15)) + ggtitle("Race distribution in ACS")



survey <- read_csv(("UCLA.csv"), col_types = cols(employment = col_character(), 
                                                             race_ethnicity = col_character(),
                                                             foreign_born = col_factor(),
                                                             gender = col_factor(),
                                                             census_region = col_factor(),
                                                             household_income = col_factor(),
                                                             age = col_factor(),
                                                             vote_2020 = col_number(),
                                                             education = col_number(),
                                                             state = col_number()
                                                             )
                 )

# AGE
AGE <- ggplot(survey, aes(x =age)) + 
  geom_bar(fill = 'steelblue', aes(y = (..count..)/sum(..count..))) + 
  scale_y_continuous(labels=scales::percent) +
  ylab("relative frequencies")+
  theme_minimal() +
  ggtitle("Age distribution in survey")



# GENDER 
GENDER <- survey  %>% group_by(gender) %>% summarise(n = n()) %>%
  mutate(prop = 100 * (n / sum(n))) 
GENDER <- GENDER %>%
  ggplot(aes(x="", y=prop, fill=gender)) +
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start=0) + 
  scale_fill_brewer(palette="Paired") +
  theme_void() + 
  ylab("") + xlab("") + 
  labs(title = "", fill="Gender ") + 
  geom_text(aes(label = paste0(round(prop), "%")), position = position_stack(vjust = 0.5), size = 4.7) +
  theme(text = element_text(size=15)) + ggtitle("Gender distribution in survey")


# EMPLOYMENT
EMP <- survey  %>% group_by(employment) %>% summarise(n = n()) %>%
  mutate(prop = 100 * (n / sum(n))) 
EMP <- EMP %>%
  ggplot(aes(x="", y=prop, fill=employment)) +
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start=0) + 
  scale_fill_brewer(palette="Paired") +
  theme_void() + 
  ylab("") + xlab("") + 
  labs(title = "", fill="employment ") + 
  geom_text(aes(label = paste0(round(prop), "%")), position = position_stack(vjust = 0.5), size = 4.7) +
  theme(text = element_text(size=15)) + ggtitle("Employment status distribution in survey")



# RACE
RACE <- survey  %>% group_by(race_ethnicity) %>% summarise(n = n()) %>%
  mutate(prop = 100 * (n / sum(n))) 
RACE <- RACE %>%
  ggplot(aes(x="", y=prop, fill=race_ethnicity)) +
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start=0) + 
  scale_fill_brewer(palette="Paired") +
  theme_void() + 
  ylab("") + xlab("") + 
  labs(title = "", fill="race ") + 
  geom_text(aes(label = paste0(round(prop), "%")), position = position_stack(vjust = 0.5), size = 4.7) +
  theme(text = element_text(size=15)) + ggtitle("Race distribution in survey")

vote_2020_prop <- survey %>% group_by(vote_2020) %>% summarise(n = n()) %>%
  mutate(prop = 100 * (n / sum(n)))
p4 <- vote_2020_prop %>% ggplot(aes(x = "", y = prop, fill = )) + 
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start = 0) +
  scale_fill_brewer(palette = "Greens") +
  theme_void() +
  ylab("") + xlab("") + 
  labs(title = "", fill="Trump") +
  geom_text(aes(label = paste0(round(prop), "%")), position = position_stack(vjust = 0.5), angle=45, size = 4.7) +
  theme(text = element_text(size=15))
p4

# Pie Chart   
slices <- c(2447,2680)
lbls <- c("Trump", "Biden")
pct <-round(slices/sum(slices)*100, digits=2)
lbls <-paste(lbls, pct)
lbls <-paste(lbls, "%", sep="")


```